services:
  - type: web
    name: ai-video-assistant

    runtime: python

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: >
      streamlit run app.py
      --server.port $PORT
      --server.address 0.0.0.0
      --server.headless true

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      - key: TOKENIZERS_PARALLELISM
        value: false

      - key: PYTORCH_JIT
        value: "0"

      - key: STREAMLIT_SERVER_HEADLESS
        value: true

      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false